<a href="https://colab.research.google.com/github/IvRodco/EstadisticaAplicasa_1899843/blob/main/Sesion3_EA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Estadistica aplicada

###Sesion 3, 10 de agosto

####Ivanna Lizeth Rodriguez Ambriz 1899843



Numpy (Numerical python) ayuda a manejar numeros en python (vectores,matrices, decimales)

La estructura basica de numpy son los arreglos(arrays), un arreglo es una coleccion de objetos del mismo tipo


Vamos a suponer que tenemos las deltas de botellas de agua de la cafeteria de la facu

Suponemos que:
El lunes de vendieron 23 botellas de agua,
el martes 45,
el miercoles 34,
el jueves 28
y el viernes 20 botellas de agua,

In [1]:
import numpy as np

In [3]:
ventas =[23,45,34,28,20]

type(ventas)

list

In [7]:
ventas= np.array(ventas)

type(ventas)

numpy.ndarray

In [8]:
#suma los elementos del arreglo

np.sum(ventas)

150

In [9]:
#multiplicacion de los elementos del arreglo
np.prod(ventas)

19706400

In [10]:
#promedio de los elementos del arreglo
np.mean(ventas)

30.0

In [11]:
#valor maximo de los elementos del arreglo
np.max(ventas)

45

In [12]:
#valor minimo de los elementos de un arreglo
np.min(ventas)

20

In [13]:
#ordena el arreglo de menor a mayor
np.sort(ventas)

array([20, 23, 28, 34, 45])

In [14]:
#varianza de los elementos del arreglo
np.var(ventas)
#esta es la varianza poblacional
#ya que python si no espeficificas el ddof lo toma como cero

78.8

In [15]:
#desviacion estandar de el arreglo
np.std(ventas)
#esta es la desviacion estandar poblacional

8.87693640846886

In [16]:
#para la varianza muestral
np.var(ventas,ddof=1)

98.5

In [17]:
#para la desviasion estandar muestral
np.std(ventas,ddof=1)

9.924716620639604

In [19]:
#crear un vector

np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
#especifica al vector de que a que numeros tomar
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [21]:
#especifica al vector de cuanto en cuanto y hasta donde
np.arange(1,100,15)
#en este caso va a contar de 15 en 15 de los numeros del 1 hasta el 100

array([ 1, 16, 31, 46, 61, 76, 91])

In [24]:
#crea un arreglo de 10 con numeros aleatorios que van del 0 al 25

#fijamos la semilla para que siempre nos genere los mismos numeros aleatorios

np.random.seed(12)
np.random.randint(0,25,10)

#genera numeros aleatorios de una distribucion uniforma

array([11,  6, 17,  2,  3,  3, 12, 16, 22, 17])